version: '3.7'

x-shared-volumes: &shared-volumes
  - ./:/app:rw
  - workspace_modules:/app/node_modules
  - workspace_yarn_cache:/home/node/.cache/yarn
  - equipment_service_modules:/app/packages/equipment-service/node_modules
  - loadout_service_modules:/app/packages/loadout-service/node_modules

services:
  equipment-service:
    build: .
    volumes:
      - ./:/app
    command: yarn --cwd packages/equipment-service start:dev
    working_dir: /app
    ports:
      - 4001:4001
    environment:
      PORT: 4001
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT: http://dynamodb:8000
    depends_on:
      - db

  db:
    image: postgres:10.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb:
    image: amazon/dynamodb-local:latest
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    ports:
      - 8000:8000
    volumes:
      - dynamodb_data:/home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb

volumes:
  workspace_modules:
  workspace_yarn_cache:
  equipment_service_modules:
  loadout_service_modules:
  postgres_data:
  dynamodb_data:
